FROM nvidia/cuda:11.3.1-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y software-properties-common && \ 
    add-apt-repository ppa:deadsnakes/ppa -y && \ 
    apt update && \ 
    apt install -y python3.9 python3.9-venv python3.9-dev git ffmpeg libsm6 libxext6

ENV VIRTUAL_ENV=/opt/venv
RUN python3.9 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip && pip install torch==1.12.1 torchvision==0.13.1 mmengine==0.10.2 openmim==0.3.9 mmsegmentation==1.2.2 regex ftfy && \ 
    pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113 && \
    pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12/index.html

RUN pip install --upgrade pip && \ 
    pip install openmim==0.3.9 timm==0.6.11 mmdet==2.28.1 opencv-python termcolor yacs pyyaml scipy numpy==1.26.4 pydantic==1.10.13


RUN git clone https://github.com/gyyang23/GCNet.git

RUN cd GCNet/mmsegmentation && pip install -v -e . && cd ..

WORKDIR InternImage

COPY . ./

ENTRYPOINT bash
